services:
  # Servicio Backend
  - type: web
    name: control-de-tareas-backend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    rootDir: controlDeTareasBackend
    dockerfilePath: controlDeTareasBackend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://db:5432/controlTareas_db
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres
      - key: SPRING_DATASOURCE_PASSWORD
        value: nieves@
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

  # Servicio Frontend
  - type: web
    name: control-de-tareas-frontend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    rootDir: controlDeTareasFrontend
    dockerfilePath: controlDeTareasFrontend/Dockerfile
    plan: free
    autoDeploy: true
    envVars: []

  # Servicio Base de Datos
  - type: pserv
    name: db
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    image:
      url: postgres:15
    plan: free
    envVars:
      - key: POSTGRES_DB
        value: controlTareas_db
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        value: nieves@