services:
  # 🚀 Backend - Spring Boot
  services:
  - type: web
    name: control-de-tareas-backend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasBackend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d3p89q56ubrc73djv1o0-a.render-database.com:5432/control_db_4lmf_psho
      - key: SPRING_DATASOURCE_USERNAME
        value: postgres_user
      - key: SPRING_DATASOURCE_PASSWORD
        value: HXa8ZxlUsZQ2W2E5hHs7UjERWjNiTHzN
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect


  # 💻 Frontend - React
  - type: web
    name: control-de-tareas-frontend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasFrontend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://control-de-tareas-backend.onrender.com
      - key: REACT_APP_IA_API_URL
        value: https://control-de-tareas-pythonapp.onrender.com

  # 🤖 Microservicio de IA - Python
  - type: web
    name: control-de-tareas-pythonapp
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasIA/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: control_db
          property: connectionString

# 🗄️ Base de datos PostgreSQL en Render
databases:
  - name: control_db
    databaseName: control_db_4lmf_psho
    user: postgres_user
    plan: free
