services:
  - type: web
    name: control-de-tareas-backend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasBackend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        value: jdbc:postgresql://dpg-d15e4fjipnbc73eaefj0-a:5432/control_db_4lmf
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: control_db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: control_db
          property: password
      - key: SPRING_DATASOURCE_DRIVER_CLASS_NAME
        value: org.postgresql.Driver
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

  - type: web
    name: control-de-tareas-frontend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasFrontend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://control-de-tareas-backend.onrender.com
      - key: REACT_APP_IA_API_URL
        value: https://control-de-tareas-pythonapp.onrender.com

  - type: web
    name: control-de-tareas-pythonapp
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasIA/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        value: jdbc:postgresql://dpg-d15e4fjipnbc73eaefj0-a:5432/control_db_4lmf

databases:
  - name: control_db
    databaseName: control_db_4lmf
    user: postgres_user
    plan: free