services:
  - type: web
    name: control-de-tareas-backend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasBackend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: SPRING_DATASOURCE_URL
        fromDatabase:
          name: control_db
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: control_db
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: control_db
          property: password
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
      - key: SPRING_JPA_SHOW_SQL
        value: "true"
      - key: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
        value: org.hibernate.dialect.PostgreSQLDialect

  - type: web
    name: control-de-tareas-frontend
    runtime: docker
    repo: https://github.com/DanielNieves04/Control-de-Tareas
    branch: main
    dockerfilePath: controlDeTareasFrontend/Dockerfile
    plan: free
    autoDeploy: true
    envVars:
      - key: REACT_APP_API_URL
        value: https://control-de-tareas-backend.onrender.com

databases:
  - name: control_db
    databaseName: control_db
    user: postgres_user
    plan: free